name: Benchmarks

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]


jobs:
  run_benchmarks:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Remove man-db to speed up apt
      run: |
        sudo apt-get remove -y --purge man-db
    - name: Setup Bind9
      run: |
        sudo apt update
        sudo apt install -y bind9
        sudo cp -R ci-data/bind9/* /etc/bind/
        sudo named -c /etc/bind/named.conf -g &

        for i in {1..10}; do
          if nc -z 127.0.0.1 53; then
            echo "BIND9 port is open!"
            break
          fi
          echo "Waiting for port 53..."
          sleep 0.3
        done

        sleep 1
        host mydomain.local 127.0.0.1
    - name: Install c-ares
      run: sudo apt install -y libc-ares2 libc-ares-dev
    - name: Run benchmarks
      run: cargo bench
